apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: banga-db
spec:
  replicas: 3
  serviceName: banga-db
  selector:
    matchLabels:
      app: banga-db
  template:
    metadata:
      labels:
        app: banga-db
    spec:
      containers:
      - name: banga-db
        image: devopseasylearning/banga-db:v0.0.1
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: db
        - name: MYSQL_ROOT_PASSWORD
          value: my-secret-pw
---
apiVersion: v1
kind: Service
metadata:
  name: banga-db
spec:
  selector:
    app: banga-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
