version: '3'

services:
  redis:
    image: redis
    environment:
      - REDIS_USER=redis
      - REDIS_PASSWORD=redis
    networks:
      - net
    volumes:
    - /vol2/data
    restart: always

  db:
    image: devopseasylearning/banga-db:v0.0.1
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    networks:
      - net
    volumes:
     - /vol1:/var/lib/mysql
    restart: always
    
    

  weather:
    image: devopseasylearning/banga-weather:v0.0.1
    depends_on:
      - db
      - redis
    environment:
      - APIKEY=ecbc396f46mshb65cbb1f82cf334p1fcc87jsna5e962a3c542
    ports:
      - "5000:5000"
    networks:
      - net
    restart: always

  auth:
    image: devopseasylearning/banga-auth:v0.0.1
    depends_on:
      - weather
    environment:
      - DB_HOST=db
      - DB_PASSWORD=my-secret-pw
    ports:
      - "8081:8080"
    networks:
      - net
    restart: always

  ui:
    image: devopseasylearning/banga-ui:v0.0.1
    depends_on:
      - auth
    environment:
      - AUTH_HOST=auth
      - AUTH_PORT=8080
      - WEATHER_HOST=weather
      - WEATHER_PORT=5000
      - REDIS_USER=redis
      - REDIS_PASSWORD=redis
    ports:
     - "3000:3000"
    networks:
      - net
    restart: always
    

networks:
  net:
    driver: bridge

